-- Migration: 003_create_assets
-- Purpose: Creates the assets table storing metadata for user-uploaded and AI-generated media.

CREATE TABLE IF NOT EXISTS public.assets (
  id                UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id           UUID        NOT NULL REFERENCES public.users_profile(id) ON DELETE CASCADE,
  filename          TEXT        NOT NULL,
  mime_type         TEXT        NOT NULL,
  size_bytes        BIGINT      NOT NULL,
  storage_path      TEXT        NOT NULL,
  folder            TEXT        NOT NULL DEFAULT '/',
  tags              TEXT[]      NOT NULL DEFAULT '{}',
  source            TEXT        NOT NULL CHECK (source IN ('user_upload', 'ai_generated')),
  generation_prompt TEXT,
  ai_model          TEXT,
  created_at        TIMESTAMPTZ NOT NULL DEFAULT now()
);

COMMENT ON TABLE public.assets IS
  'Metadata for uploaded and generated media assets owned by users.';
COMMENT ON COLUMN public.assets.folder IS 'Virtual folder path used for asset organization.';
COMMENT ON COLUMN public.assets.source IS 'Asset origin: uploaded by user or generated by AI.';
